Add friends likes
UserNameToHub/java-filmorate pull request #3
Opened 2023-04-28 22:24 UTC by UserNameToHub

Привет! Посмотри пжл!

2023-04-29 04:12 UTC, EugeneLenkevich requested changes
Привет, Александр, спасибо за PR

Все здорово, особенно понравился подход с интерфейсами для репозиториев, единственное, хотелось бы логирование бизнес операций преенести в сервисы, чтобы у нас разделение обязаностей между слоями было совсем четкое :)

2023-04-29 04:12 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Запрос на получение списка всех фильмов из базы.");
А что если перенести то логирование в сервис, оно больше похоже на описание бизнес-логики, а в контроллере у нас только обработка http-запросов, в сервисе было бы логичнее делатьтакое логирование, как думаешь?

2023-04-29 04:12 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +    public FilmServiceImpl(InMemoryFilmRepository filmRepository, UserServiceImpl userService) {
Можно, кстати, не задавать руками конструктор, можно добавить аннотацию lombok @RequiredArgsConstroctor :)

2023-04-29 04:12 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +        if (userRepository.findById(type.getId()).isPresent()) {
А что если сделать вот такй метод, который проверяет сущестование записи и возвращает булево значение да/нет вместо того чтобы вытаскивать всю запись, думаю будет более наглядно :)
userRepository.existsById(type.getId())

2023-04-30 11:38 UTC, UserNameToHub commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Запрос на получение списка всех фильмов из базы.");
Изначально все логи были в service слое, но чет я перемудрил) 
Спасибо!

2023-04-30 11:42 UTC, UserNameToHub commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +    public FilmServiceImpl(InMemoryFilmRepository filmRepository, UserServiceImpl userService) {
Точно, он же инициализирует все final поля) Спасибо!

2023-04-30 11:53 UTC, UserNameToHub commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServiceImpl.java
> +        if (userRepository.findById(type.getId()).isPresent()) {
Согласен, смысл тянуть всю запись, если нам нужо только проверить, а не использовать. Спасибо!

2023-04-30 13:14 UTC, EugeneLenkevich approved these changes
Ага, отлично, спасибо!

2023-05-29 00:11 UTC, merged